version: '3.8'
services:
  # Laravel用コンテナ
  app:
    build:
      context: docker/laravel-11-react/
      dockerfile: Dockerfile
    container_name: laravel_11_react_app
    # ローカルのプロジェクトディレクトリをコンテナにマウント
    volumes:
      - ./laravel-11-react:/var/www/html
    ports:
      - "82:80"
    depends_on:
      - db
    # 環境変数を必要に応じて追加できます
    environment:
      # Laravel アプリケーションで DB 接続するための設定例
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: user
      DB_PASSWORD: password

  # MySQLコンテナ
  db:
    image: mysql:8
    container_name: laravel_11_react_app_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    # データを永続化するためにボリュームを設定
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3308:3306"

  # phpMyAdmin コンテナ
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password

# ここで定義したボリュームを DB で使います
volumes:
  db-data: