version: '3.8'
services:
  # Laravel用コンテナ
  app:
    build:
      context: docker/laravel-11-react/
      dockerfile: Dockerfile
    container_name: laravel_11_react_app
    # ローカルのプロジェクトディレクトリをコンテナにマウント
    volumes:
      # - ./laravel-11-react:/var/www/html
      - ./laravel-11-react/app:/var/www/html/app
      - ./laravel-11-react/bootstrap:/var/www/html/bootstrap
      - ./laravel-11-react/config:/var/www/html/config
      - ./laravel-11-react/database:/var/www/html/database
      - ./laravel-11-react/node_modules:/var/www/html/node_modules
      - ./laravel-11-react/public:/var/www/html/public
      - ./laravel-11-react/resources:/var/www/html/resources
      - ./laravel-11-react/routes:/var/www/html/routes
      - ./laravel-11-react/storage/logs:/var/www/html/storage/logs
      - ./laravel-11-react/storage/app:/var/www/html/storage/app
      - ./laravel-11-react/tests:/var/www/html/tests
      - ./laravel-11-react/.editorconfig:/var/www/html/.editorconfig
      - ./laravel-11-react/.env:/var/www/html/.env
      - ./laravel-11-react/.env.example:/var/www/html/.env.example
      - ./laravel-11-react/artisan:/var/www/html/artisan
      - ./laravel-11-react/composer.json:/var/www/html/composer.json
      - ./laravel-11-react/composer.lock:/var/www/html/composer.lock
      - ./laravel-11-react/package.json:/var/www/html/package.json
      - ./laravel-11-react/package-lock.json:/var/www/html/package-lock.json
      - ./laravel-11-react/phpunit.xml:/var/www/html/phpunit.xml
      - ./laravel-11-react/postcss.config.js:/var/www/html/postcss.config.js
      - ./laravel-11-react/tailwind.config.js:/var/www/html/tailwind.config.js
      - ./laravel-11-react/vite.config.js:/var/www/html/vite.config.js
    ports:
      - "82:80"
    depends_on:
      - db
    # 環境変数を必要に応じて追加できます
    environment:
      # Laravel アプリケーションで DB 接続するための設定例
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: user
      DB_PASSWORD: password

  # MySQLコンテナ
  db:
    image: mysql:8
    container_name: laravel_11_react_app_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    # データを永続化するためにボリュームを設定
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3308:3306"

  # phpMyAdmin コンテナ
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password

# ここで定義したボリュームを DB で使います
volumes:
  db-data: